name: ecomp_analysis
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip
- ipython
- ipykernel
- numpy
- scipy
- pandas
- matplotlib
- pre-commit
- black
- isort
- flake8
- flake8-docstrings
- pytest-cov
- pytest-sugar
- pytest
- pip:
  - mne
  - git+https://github.com/mne-tools/mne-qt-browser.git@06e586a44fc7934b14ad7c0cde89f527bafbd879
  - psutil
  - pyopengl
  - pingouin
  - statsmodels
