name: ecomp_analysis
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip
- ipython
- ipykernel
- numpy<1.23
- scipy<1.9
- pandas<1.5
- pingouin<0.6
- statsmodels<0.14
- matplotlib<3.6
- seaborn<0.12
- mne-faster
- mne-qt-browser
- python-picard
- pyprep
- psutil
- numba
- tqdm
- pre-commit
- black
- isort
- flake8
- flake8-docstrings
- git-annex
- h5py
- h5io
- pip:
  - mne<1.1
  - pooch
  - pyopengl
  - pyyaml
  - datalad
