name: ecomp_analysis
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip
- ipython
- ipykernel
- numpy
- scipy
- pandas
- matplotlib
- numba
- pre-commit
- black
- isort
- flake8
- flake8-docstrings
- pytest-cov
- pytest-sugar
- pytest
- git-annex
- pip:
  - https://github.com/mne-tools/mne-python/zipball/6e312e1254105b9f2546c3b91108b1f96b7f05c3
  - pooch
  - tqdm
  - python-picard
  - pyprep
  - mne-faster
  - mne-qt-browser
  - psutil
  - pyopengl
  - pingouin
  - statsmodels
  - pyyaml
  - datalad
